services:
  db:
    image: postgres:15-alpine
    restart: always
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_USER: geotime
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: geotime
    ports:
      - "5433:5432"