"""init migration

Revision ID: 6a33c3f288a8
Revises: 
Create Date: 2025-01-17 09:25:06.487407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a33c3f288a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ROTOR', 'MOSTKI', 'SITA', 'PVO', 'ROTOR2', 'AMBAR', 'KABINA', name='cameraname'), nullable=True),
    sa.Column('rtps_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_index(op.f('ix_cameras_name'), 'cameras', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
